name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  esp_idf_build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: 'x64'
    - name: Run unit test
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: linux
        path: 'test'
        command: ./run.sh
